freight:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: freight_dev
      schema: default
      host: "{{ env_var('DBX_HOST') }}"
      http_path: "{{ env_var('DBX_HTTP_PATH') }}"
      token: "{{ env_var('DBX_TOKEN') }}"
      threads: 8

    prod:
      type: databricks
      catalog: freight_prod
      schema: default
      host: "{{ env_var('DBX_HOST') }}"
      http_path: "{{ env_var('DBX_HTTP_PATH') }}"
      token: "{{ env_var('DBX_TOKEN') }}"
      threads: 8

    ci:
      type: databricks
      catalog: freight_ci
      schema: default
      host: "{{ env_var('DBX_HOST') }}"
      http_path: "{{ env_var('DBX_HTTP_PATH') }}"
      token: "{{ env_var('DBX_TOKEN') }}"
      threads: 8
